# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dash', '0006_auto_20170610_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IntrestRate', models.IntegerField(default=8)),
                ('AllotedCredit', models.IntegerField(default=0)),
                ('LoanNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.dashboard')),
            ],
        ),
    ]
