# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeloan',
            old_name='LoanNo',
            new_name='key',
        ),
        migrations.AddField(
            model_name='homeloan',
            name='LoanNO',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
