# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20170610_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeloan',
            name='id',
        ),
        migrations.AlterField(
            model_name='homeloan',
            name='LoanNO',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
