# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_auto_20170610_0544'),
        ('loan', '0003_auto_20170610_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarLoan',
            fields=[
                ('LoanNO', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('IntrestRate', models.IntegerField(default=8)),
                ('AllotedCredit', models.IntegerField(default=0)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.dashboard')),
            ],
        ),
    ]
