# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_carloan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeloan',
            old_name='key',
            new_name='dashboard',
        ),
    ]
