# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_auto_20170610_0544'),
        ('mutualfunds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.FloatField(default=0)),
                ('Investment', models.FloatField(default=0)),
                ('IntrestRate', models.FloatField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.dashboard')),
            ],
        ),
    ]
