# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_dashboard_accountno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='id',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='accountno',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
