# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20170520_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InsurencePolicy', models.IntegerField(default=0)),
                ('MutualFund', models.IntegerField(default=0)),
                ('FixedDeposite', models.IntegerField(default=0)),
                ('loan', models.IntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.dashboard')),
            ],
        ),
    ]
