# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='loan',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
